### ISSUE TITLE
Focus Pan/Tilt attributes 

### ISSUE THREAD

**Issue by tourkit** [mvrdevelopment/spec#100]
![image](https://user-images.githubusercontent.com/63537158/142989216-70feea11-8a7b-4336-8633-f8a8b7864cc2.png)

At the moment you can only pass a UUID for a FocusPoint, but it would great to have Pan & Tilt too .as ni some cases you'd need one FocusPoint per fixture ....

thx

**Comment by LxLasso** [comment]
Just having a pan and tilt value doesn't really work because it needs to be relative to something. It's also missing out on axial orientation.

Unfortunately the orientation of fixtures in an MVR is largely undefined at the moment. Someone would have to spend the time on understanding how fixtures are oriented in the relevant software on the market and then write down a solution that makes it possible to convey this information between all these softwares in an unambiguous way. At the moment MVR is simply tailored to VectorWorks' needs.

**Comment by moritzstaffel** [comment]
> Unfortunately the orientation of fixtures in an MVR is largely undefined at the moment. Someone would have to spend the time on understanding how fixtures are oriented in the relevant softwares on the market and then write down a solution that makes it possible to transport this information between all these softwares in an unambiguous way (if that's even possible). At the moment MVR is simply tailored to VectorWork's needs and it matches other softwares' needs poorly.
The position and orientation of a fixture is defined by the GDTF linked by the GDTF. This also defines all the other stuff.
So the work on this is already done. 

To transfer pan and tilt orientation, you currently need use focus points. For the next MVR version we want to support Pan and Tilt like @tourkit has proposed. 

I think MVR works fine if you use GDTF with it to express the definition of the fixtures.

**Comment by LxLasso** [comment]
As you know GDTF is unusable for us in its current state.

What you intend to make pan and tilt relative?

**Comment by moritzstaffel** [comment]
The MVR Pan Tilt will be based on the GDTF definition for the Pan and Tilt functionality.

We are currently thing about making them percentage based to that you can use the GDTF Channel Function to calculate the  Pan/Tilt or that you can give an absolute value.

That approach is similar to the support of OSC that we have added to GDTF1.2.

All the definition is already in the GDTF. MVR and GDTF are designed to work together. So only together they give you the full feature set.

**Comment by RichardTea** [comment]
Well, that doesn't work for anyone at all then. Not even Vectorworks. :(

**Comment by LxLasso** [comment]
As long as the whole concept is based on the idea of all softwares involved natively relying on GDTF files it's all rather shot I'm afraid. It might be a vision for the future, but here and now it renders MVR a pretty pointless exercise. If it wasn't the only way of reading designs from VectorWorks or getting patch into MA3 we wouldn't have touched it.

**Comment by moritzstaffel** [comment]
MVR and GDTF are designed to work together. Just using MVR is like using a car without engine.

GDTF has all the technical information to do the Pan and Tilt features, even when you don't use GDTF as native fixture type in the software, you can calculate the resulting Pan and tilt.

In ChamSys, MA3, Vision and Vectorworks software product the GDTF exchange works pretty good.

**Comment by moritzstaffel** [comment]
Implemented by the 1.5 MVR Version
