### ISSUE TITLE
MVR: "ScaleHandeling" is spelt incorrectly

### ISSUE THREAD

**Issue by RichardTea** [mvrdevelopment/spec#110]
This should be `ScaleHandling` throughout.

However, I would recommend `ScaleMode` instead as that's more descriptive of what it (apparently) actually does.

The definition also requires a description and pictographic examples of what is meant by each value, the value name alone is not sufficient to understand what is intended.

For example, see Qt's documentation:
https://doc.qt.io/qt-5/qt.html#AspectRatioMode-enum

**Comment by moritzstaffel** [comment]
Do we want to do this

**Comment by moritzstaffel** [comment]
https://github.com/mvrdevelopment/spec/commit/6a42b51521c30a33a55389a9a78fdb5c2d4bd0c3

I have added the examples, but the spelling mistakes remains for compatibility reasons.
