### ISSUE TITLE
Define DMXProfile for DMXProfiles

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#13]
With defining more and more real world parameters, we have good opportunity to explore addition of DMXProfiles.

Currently, we do need to specifically apply curves to rotations with angular speeds, in order to have proper visualization. Right now, we define multiple channel sets, which are then linearly interpolated. This works well but DMXProfiles would be proper solution.

My first look opinions:

- DMXProfiles collect
    - DMXProfile collect with attributes Name, InterpolationTo (enum like in measurements?)
        - Point with attributes DMX, Value

Then we need to be able to define a link between ChannelFunction and a DMXProfile.
![a](https://user-images.githubusercontent.com/45997318/80520327-8ef27280-8989-11ea-8d8e-82840c7c9ef1.png)
![image_2020_04_28T12_30_16_839Z](https://user-images.githubusercontent.com/45997318/80520331-90239f80-8989-11ea-8367-bc589168067a.png)
![image_2020_04_28T11_26_42_303Z](https://user-images.githubusercontent.com/45997318/80520334-90bc3600-8989-11ea-89e6-0fcbdf6ea979.png)

**Comment by moritzstaffel** [comment]
GDTF Profiles have been created for version 1.2
