### ISSUE TITLE
Small changes on DMXChannel xml attribute "Offset"

### ISSUE THREAD

**Issue by danielmuellerma** [mvrdevelopment/spec#14]
suggestions by @AndriiVoitenko 
-add "Array of Int" to value type table and specify separator there.
-Special value can be removed - if there is no "Offset" defined it is a virtual channel.
-add to description that count of addresses defines resolution of the DMXChannel.
-add that virtual channel has a resolution of 32bit.
-to be discussed: define limitation for length of offset array

**Comment by moritzstaffel** [comment]
This seems to be done
