### ISSUE TITLE
GDTFSpec and GDTFMode children in MVR

### ISSUE THREAD

**Issue by s-montanus** [mvrdevelopment/spec#145]
Currently the nodes `SceneObject`, `Truss`, `Fixture`, `Support`, `Projector` and `VideoScreen` all have an optional ( 0 or 1 ) `GDTFSpec` child node,
Shouldn't the `GDTFSpec` child be mandatory for `Fixture`, `Projector` and `VideoScreen` nodes ?

Also the nodes with an optional `GDTFSpec` child have a mandatory `GDTFMode` child.
Shouldn't the `GDTFMode` be mandatory if and only if the `GDTFSpec` is present ?
And isn't it then more logical to have the `GDTFMode` node be a child of the `GDTFSpec` node ?

**Comment by moritzstaffel** [comment]
https://github.com/mvrdevelopment/spec/commit/d84903956aee40ee7b5afbdec59c0224383d9843

**Comment by moritzstaffel** [comment]
>Also the nodes with an optional GDTFSpec child have a mandatory GDTFMode child.
>Shouldn't the GDTFMode be mandatory if and only if the GDTFSpec is present ?
>And isn't it then more logical to have the GDTFMode node be a child of the GDTFSpec node ?

Yes that is true. But as we don't want to break Backward Compatibly, I would not change it. But I have clarified for the spec, the relation between this.

> Shouldn't the GDTFSpec child be mandatory for Fixture, Projector and VideoScreen nodes ?
We want to allow to define this objects still by Geometry mode. And we want to align the behavior between the objects types.
The same thing applies for trusses for example. When you define the structure in the GDTF, you could calculate the truss. 
But I think we need to make this a step by step transmission.
