### ISSUE TITLE
GDTF files edited and provided via MVR

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#146]
1) When a GDTF file is modified and exported to GDTF, often there is no revision - indicating this change - added, thus the user may think that the file is the original one as provided (by the manufacturer). Revisions are optional and at this point are only enforced upon uploading to the Share. We should add a mandatory revision requirement to make it clear that the file has been modified.

2) Shouldn't the GDTFSpec → FileName be more closely aligned to the GDTF counterpart? https://github.com/mvrdevelopment/spec/blob/main/gdtf-spec.md#file-format-definition . To the point above, the revision of the file is suggested to be part of the file name.

3) GDTFSpec → FileName does not specify that the extension must be part of the FileName. We have seen issues in the past with GDTF resource files which used upper case or mixed upper/lower case in the extension. It would be good to remove this ambiguity, by requiring the extension to be part of FileName.

4) General GDTF quality issues caused by modifications and subsequent export to MVR: 

- completely removed files or folders
- files moved to (wrong) directories
- data itself being modified, making the GDTF unreliable and thus loosing trust of the user into provided data

This is more on quality/process which is hard to capture and enforce, yet the user experience is strongly downgraded if that happens and we should put emphasis on ensuring that data quality is protected.

**Comment by moritzstaffel** [comment]
> Shouldn't the GDTFSpec → FileName be more closely aligned to the GDTF counterpart? https://github.com/mvrdevelopment/spec/blob/main/gdtf-spec.md#file-format-definition . To the point above, the revision of the file is suggested to be part of the file name.

Already by the spec

**Comment by moritzstaffel** [comment]
> GDTFSpec → FileName does not specify that the extension must be part of the FileName. We have seen issues in the past with GDTF resource files which used upper case or mixed upper/lower case in the extension. It would be good to remove this ambiguity, by requiring the extension to be part of FileName

Day by the spec already
