### ISSUE TITLE
Add spectral data collect for lamp

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#16]
In order to calculate colors, one will need to have spectrum of the lamp. This should not be too complex to add, if we use current emitter/filer collect and extend it to "lamp", with similar spectral data as per emitter/filter specification.

Likely, we will want to link it to beam geometry (if Lamp Type != LED)

@moritzstaffel do you agree? We can wait for @danielmuellerma , when he is back, i just want to make sure we track it.

**Comment by moritzstaffel** [comment]
Already done https://github.com/mvrdevelopment/spec/blob/main/gdtf-spec.md#geometry-type-beam
