### ISSUE TITLE
Allow to define a color for a single color emitter

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#160]
It is currently not possible to describe a fixture that has colored emitter (f.e. blue) and a for example shutter, if these attributes are on a single channel:

![image](https://github.com/mvrdevelopment/spec/assets/45997318/bb943373-d392-4304-aaf9-0847a6262140)

We could do this by adding an Emitter Spectrum to the Beam geometry, but the Spec is now very explicit, defining that the spectrum is for subtractive color mixing only:

![image](https://github.com/mvrdevelopment/spec/assets/45997318/2a3dacd6-984b-4626-82ca-b35cf3b266c1)

**Comment by moritzstaffel** [comment]
>Optional link to emitter in the physical description; use this to define the white light source of a subtractive color mixing system **or the default light source for the beam.** Starting point: Emitter Collect; Default spectrum is a Black-Body with the defined ColorTemperature.

**Comment by moritzstaffel** [comment]
The idea here is that you define a "color" for a light source that is not white.
