### ISSUE TITLE
Lamp type Plasma, Laser, Other

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#166]
Add additional lamp types:

- "Plasma" for devices like Robe Plasma Spot 
- "Laser" for fixtures with laser source
- Perhaps also add lamp type "Other" to cover currently unknown/not described light sources

**Comment by moritzstaffel** [comment]
| XML Attribute Name  | Value Type                            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|----|----|----|
| LampType            | [Enum](#user-content-attrtype-enum )     | Defines type of the light source; The currently defined types are: Discharge, Tungsten, Halogen, LED; Default value “Discharge”                                                                                                                                                                                                                                                                                                                                                                                                                          |


-> 

| XML Attribute Name  | Value Type                            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|----|----|----|
| LampType            | [Enum](#user-content-attrtype-enum )     | Defines type of the light source; The currently defined types are: Discharge, Tungsten, Halogen, LED, Plasma, Laster, Other; Default value “Discharge”                                                                                                                                                                                                                                                                                                                                                                                                                          |

**Comment by moritzstaffel** [comment]
The beam type currently does not do very much, `BeamType` should define how hotspoty a beam it. 
The LampType seems to most useful for the default Color Temperature. 

So what kind of color temperature would a Laser or Plasma fixture has by default?

**Comment by moritzstaffel** [comment]
We need to create the Pull, this will be done by me @moritzstaffel

**Comment by moritzstaffel** [comment]
Merged
