### ISSUE TITLE
Remove male/female from predefined connectors as Sex is a property of the connector in connector collect

### ISSUE THREAD

**Issue by danielmuellerma** [mvrdevelopment/spec#22]
e.g.
XLR3F | 3-pin female XLR
XLR4M | 4-pin male XLR
XLR4F | 4-pin female XLR
XLR5M | 5-pin male XLR
XLR5F | 5-pin female XLR
DB9M | 9-pin male D-type
DB9F | 9-pin female D-type
DB15M | 15-pin male D-type
DB15F | 15-pin female D-type

In my opinion, we do not need to distinguish here between m and f because we have a property for this.

**Comment by moritzstaffel** [comment]
This already has been done.

**Comment by moritzstaffel** [comment]
https://github.com/mvrdevelopment/spec/blob/main/gdtf-spec.md#annex-d-informative-predefined-connector-types
