### ISSUE TITLE
Allow file author to choose prefered Name for Channel/Channel Function/Wheel

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#27]
Have the user to see in the console what they are expected to see based on manufacturer's DMX charts.

Right now, it is possible to do it this way, but it is not enforced. Sequentially:

- name is taken from GDTF defined list of Fixture Type Attributes (Attribute Name and Attribute Pretty)
- name is taken from value of Name of first Channel Function of a Logical Channel
- name is taken from value of OriginalAttribute of first Channel Function of a Logical Channel

Nowhere, the file author (design studio, system integrator or fixture manufacturer) has a clear way to define "this is what the user will see". We must change this.

**Comment by moritzstaffel** [comment]
This is more display on the console than the actual spec work. 

GDTF has a universal view on this, also allows this custom names. But how this is than displayed on individual consoles / UI implementation is a little out of reach.
