### ISSUE TITLE
MVR: Addresses (integer) need more detailed definition

### ISSUE THREAD

**Issue by danielmuellerma** [mvrdevelopment/spec#3]
https://gdtf-share.com/forum/index.php?/topic/376-fixture-addresses/

0 is intended to be "not patched"
integer is 1 based

**Comment by LxLasso** [comment]
Actually pretty much all of the fields need more detailed definitions. Unless you have intimate knowledge of VectorWorks and how it exports these fields it's anyone's guess what they are meant for.

**Comment by danielmuellerma** [comment]
this has been improved
