### ISSUE TITLE
MVR: Fixture filters

### ISSUE THREAD

**Issue by LxLasso** [mvrdevelopment/spec#50]
Filters added to conventional fixtures are an important aspect to theatrical lighting design. It should be possible to list a number of filters added to each fixture. This includes frost filters.

**Comment by moritzstaffel** [comment]
This is possible with the CIE Color of a fixture defined in MVR. The listing of the filters is possible with the GDTF.

The support for a frost filter is a good idea.

**Comment by LxLasso** [comment]
We could bake filters into a CIE Color in the MVR, but noone on the receiving end could reverse engineer which the filters were. Putting the filters in the GDTF seems odd, this would create a new unique GDTF file for any combination of filters in the design.

What is needed is a way of combining a GDTF file with a list of accessories, such as filters, gobos, shutter parameters etc. This all exists in CSV file exports from lighting design softwares today.

**Comment by moritzstaffel** [comment]
> We could bake filters into a CIE Color in the MVR, but noone on the receiving end could reverse engineer which the filters were. Putting the filters in the GDTF seems odd, this would create a new unique GDTF file for any combination of filters in the design.
You are right here. I think we need to do a similar thing like we did for the connector. So define a list of the most common used filters as string, and then add them as a flag to the fixture. As this is different per fixture, I think the property for this should be really in MVR.

**Comment by LxLasso** [comment]
> define a list of the most common used filters

That's bound to end up with every filter that exists. Rosco, LEE and Apollo together are around 2000 filters. Would you ultimately not end up having to replicate all existing filters in all fixtures?

I would add a collection of filter names to the MVR:
```
  ..
  <Color>..</Color>
  <Filters>
    <Filter>R344</Filter>
    <Filter>R119</Filter>
  </Filters>
</Fixture>
```

(And similarly for gobos, which would be even harder to narrow down to commonly used ones.)
