### ISSUE TITLE
Add additional attributes

### ISSUE THREAD

**Issue by danielmuellerma** [mvrdevelopment/spec#65]
DimmerReset - Resets the fixture's dimmer

**Comment by petrvanekrobe** [comment]
DigitalZoom/ImageScaling

changes image size within defined projection:

- used on digital projection based devices
- when "zooming down", image is smaller (like regular zoom)
- when zooming up, image is made larger but it is trimmed by the projection

**Comment by danielmuellerma** [comment]
GoboWheelShortcutMode - Defines whether the gobo wheel takes the shortest distance between two positions.

**Comment by danielmuellerma** [comment]
Add attributes to describe the fixture's shutter where one channel defines the strobe mode while another defines the frequency/rate/duration of the strobe.

We already have StrobeDuration and StrobeRate.

We should add:
StrobeFrequency
StrobeModeShutter
StrobeModeStrobe
StrobeModePulse
StrobeModePulseOpen
StrobeModePulseClose
StrobeModeRandom
StrobeModeRandomPulse
StrobeModeRandomPulseOpen
StrobeModeRandomPulseClose
StrobeModeRandomPulseEffect

**Comment by danielmuellerma** [comment]
Add activation group for Rot_X, Rot_Y, Rot_Z
