### ISSUE TITLE
Name and version of software that created the MVR file

### ISSUE THREAD

**Issue by LxLasso** [mvrdevelopment/spec#70]
Now that we are shipping Capture 2021 with MVR import we are getting a fair amount of support tickets for broken and incorrect MVR files. If the MVR file had contained structured information about the software / version that generated it, we could both show warnings in Capture and our support staff could quickly tell whether a given problem is likely caused by the software generating the MVR file.

In the meanwhile we will be putting an XML comment in the GeneralSceneDescription.xml file with this information so that support staff of our companies can tell if an MVR file came from Capture and if so, which version.

**Comment by moritzstaffel** [comment]
That is a good idea

**Comment by moritzstaffel** [comment]
https://github.com/mvrdevelopment/spec/commit/4aa870e32d198c59a49ab89c4f125033c808d806

**Comment by moritzstaffel** [comment]
Add to the DIN SPEC
