### ISSUE TITLE
Virtual DMX Channels not accepted in the offset pattern

### ISSUE THREAD

**Issue by fbeasse** [mvrdevelopment/spec#71]
We received a ticket for the builder with this log:

Robe_Lighting@pixelPATT@15012021v3.gdtf

/dev/stdin:2762: element DMXChannel: Schemas validity error : Element 'DMXChannel', attribute 'Offset': [facet 'pattern'] The value '' is not accepted by the pattern 'None\|([0-9]+(,[0-9]+)*)'.

After checking the file, it corresponds to every virtual channel of this fixture, which has an empty string for an offset.

[Robe_Lighting@pixelPATT@15012021v3.gdtf.zip](https://github.com/mvrdevelopment/spec/files/6147561/Robe_Lighting%40pixelPATT%4015012021v3.gdtf.zip)

**Comment by moritzstaffel** [comment]
@Firionus Virtual Channels are allowed to have an empty array here.

**Comment by Firionus** [comment]
> @Firionus Virtual Channels are allowed to have an empty array here.

Sorry to hold your own standard against you, but DIN 15800:2020-07, page 33, Table 46 describes the XML attribute `Offset` of value type `Array of Int` as:

>Relative addresses of the current DMX channel from highest to least significant; Seperator of values is ","; Special value: “None” – does not have any addresses; Default value: “None”; Size per int: 4 bytes

Therefore, this field must either be some `Int`s (an empty string is not a valid Int) or be "None". Empty String is not allowed here and should be replaced by "None". 

-> I can confirm this as a bug in GDTF Builder.

**Comment by moritzstaffel** [comment]
Your're right with the None value. I did not had this on my mind. It maked sense when we still named the Offset Node different.

I think we should allow booth the empty string and the None Value. I will check if the builder handles the `None` correctly.
The empty string will be the default way to print this. But we need to clarify this in the examples of the spec.

@Firionus Thanks for the Feedback.
