### ISSUE TITLE
Clarify ChannelFunction Default Name

### ISSUE THREAD

**Issue by Firionus** [mvrdevelopment/spec#75]
**Problem**
The Default Name for a `ChannelFunction` is not described clearly in the DIN 15800:2020-07. 

Current definition of the `ChannelFunction/@Name`:

> Name
Name
Unique name; Default value: Name of attribute and number of channel function.

(quoted from Table 48 on page 34). In this current definition it is not clear how attribute and number are separated and what the number of channel function is supposed to be. 

**Proposal**

Adopt the current default value used in the GDTF Builder as standard. Clarify this by changing the description to:

> Name
Name
Unique name within the Logical Channel; Default value: Name of Attribute and 1-based index of Channel Function inside the Logical Channel, separated by a space; Example: "Dimmer 1".

**Alternatives**

Make `ChannelFunction/@Name` a required attribute by not specifying a Default value for it. This would simplify the standard, but breaks backward compatibility more strongly than the above proposal. 

**Additional context**

Previously discussed in #64

**Comment by moritzstaffel** [comment]
Clarified in the spec. Thanks for the work on this.
