### ISSUE TITLE
Move "Edit DMX Mode" button AWAY from Delete!!!

### ISSUE THREAD

**Issue by PSchulze-ARRI** [mvrdevelopment/spec#76]
Having the two options right next to each other is quite dangerous if your mouse slips a bit.  Can we move the "edit" to the left margin, since I don't see a way to Undo a delete?
![image](https://user-images.githubusercontent.com/81581089/112890091-48bafd00-908b-11eb-9657-7420f72a3f83.png)

**Comment by petrvanekrobe** [comment]
Thank you @PSchulze-ARRI , I opened a ticket 201115 for this.

**Comment by PSchulze-ARRI** [comment]
Save me from myself!!!!
P


_______________________________________________________
Patrick 
Schulze
Lighting Systems Engineer
​
ARRI Inc.
3700 Vanowen Street
Burbank, CA 91505
www.arri.com 

818-841-7070
***@***.***

Get all the latest information from www.arri.com, Facebook, Twitter, Instagram and YouTube.


​

​

This message is confidential. It may also be privileged or otherwise protected by work product immunity or other legal rules. If you have received it by mistake, please let us know by e-mail reply and delete it from your system; you may not copy this message or disclose its contents to anyone. Please send us by fax any message containing deadlines as incoming e-mails are not screened for response deadlines. The integrity and security of this message cannot be guaranteed on the Internet.

**Comment by moritzstaffel** [comment]
We now ask gif you want to delete the DMX Mode:)
