### ISSUE TITLE
Define material property of geometry

### ISSUE THREAD

**Issue by petrvanekrobe** [mvrdevelopment/spec#82]
In some places, indicating that beam is a mirror could be beneficial (not only for moving mirrors, which can currently be already specified), but for other devices, that might utilize mirrors even more.

Also, if a device is a glass box (fully transparent, but mechanically blocking/taking space), a beam inside this glass box will not leave the geometry.

With that, one could specify reflectivity and/or transparency of this material.

**Comment by klinzey** [comment]
@petrvanekrobe  The geometry should currently support transparent textures and/or the use of an alpha channel. I know Vision uses the Alpha channel of the texture to allow transparency but it's up to the application to support and recognize the transparency of the texture.

**Comment by petrvanekrobe** [comment]
Thank you @klinzey . Let me thus close it as solved by https://github.com/mvrdevelopment/spec/pull/68.
