### ISSUE TITLE
Delimiter for DMXChannel Allows Non-Unique Channel Names

### ISSUE THREAD

**Issue by Firionus** [mvrdevelopment/spec#92]
**Problem**

The following clash of DMXChannel names is not prohibited by the GDTF standard:
- DMXChannel 1: "a_b_c" (Geometry "a_b", Attribute "c")
- DMXChannel 2: "a_b_c" (Geometry "a", Attribute "b_c")

This is because the Name Type allows underscores, which are also used as a delimiter between Geometry and Attribute for the name of the DMXChannel. 

**Proposed Solution**

Require in the standard that DMXChannel Names as computed from Geometry and Attribute of the first Logical Channel must be unique. 

**Alternative Solutions**

- Disallow underscores (U+005F) in the Name Type. This has the disadvantage of breaking existing Attribute Definitions like `CIE_X`, `ColorRGB_Red`, etc.
- Change the Delimiter for the Channel Name to one of the characters that are already disallowed, which are `!` `$` `.` `&` `,` `?` `[` `\` `]` `^` `{` `|` `}` `~` `␡`.

**Comment by nicavolites** [comment]
Personally I would prefer the proposed solution or changing the Geometry name to a different type that has does not permit underscore.  The alternative solutions will impact parsing.

**Comment by moritzstaffel** [comment]
I think the proposed version is good. 

I think we never made it clear in the Spec that we assume this. Have have added this in the new proposal for the spec. 
<img width="1394" alt="Bildschirmfoto 2021-08-25 um 14 41 53" src="https://user-images.githubusercontent.com/13522639/130792355-62bbc9fa-0b7d-4371-bbfb-30fc57aaeff1.png">

here is the proposed change on the Spec text. 

Note that you can get the full spect text here: https://www.beuth.de/de/technische-regel/din-spec-15800/324748671
That is currently the only place where you find the full spec online.

**Comment by nicavolites** [comment]
Looks good to me.  As a minor point I think 'consists' should be 'consist'.
